export const SET_GOOGLE_USER_INFO = 'SET_GOOGLE_USER_INFO';
export const DELETE_GOOGLE_USER_INFO = 'DELETE_GOOGLE_USER_INFO';
export const SET_GOOGLE_IS_INITIALIZING = 'SET_GOOGLE_IS_INITIALIZING';
export const SET_GOOGLE_IS_INITIALIZED = 'SET_GOOGLE_IS_INITIALIZED';
export const SET_GOOGLE_AUTH_INFO = 'SET_GOOGLE_AUTH_INFO';
export const DELETE_GOOGLE_AUTH_INFO = 'DELETE_GOOGLE_AUTH_INFO';
