export const SET_HOTEL_REF_NO = 'SET_HOTEL_REF_NO'
export const DELETE_HOTEL_REF_NO = 'DELETE_HOTEL_REF_NO'

export const SET_HOTEL_NAME = 'SET_HOTEL_NAME'
export const DELETE_HOTEL_NAME = 'DELETE_HOTEL_NAME'

export const UPDATE_HOTEL_REF_NO = 'UPDATE_HOTEL_REF_NO'
export const UPDATE_HOTEL_NAME = 'UPDATE_HOTEL_NAME'

export const SET_HOTEL_REF_NO_IS_INITIALIZING = "SET_HOTEL_REF_NO_IS_INITIALIZING"

export const SET_LICENCE_MENU_STATUS = "SET_LICENCE_MENU_STATUS"
export const UPDATE_LICENCE_MENU_STATUS = "UPDATE_LICENCE_MENU_STATUS"

export const DELETE_CURRENT_HOTEL_INFO = 'DELETE_CURRENT_HOTEL_INFO'
export const DELETE_LICENCE_MENU_STATUS = "DELETE_LICENCE_MENU_STATUS"
