export const SET_OREST_USER_INFO = 'SET_OREST_USER_INFO'
export const DELETE_OREST_CURRENT_USER_INFO = 'DELETE_OREST_CURRENT_USER_INFO'

export const SET_OREST_IS_INITIALIZING = 'SET_OREST_IS_INITIALIZING'

export const SET_OREST_WIKI_LIST = 'SET_OREST_WIKI_LIST'
export const DELETE_OREST_WIKI_LIST = 'DELETE_OREST_WIKI_LIST'

export const SET_OREST_STATE = 'SET_OREST_STATE'
export const RESET_OREST_STATE = 'RESET_OREST_STATE'
