export const SET_SURVEY_ANSWER = 'SET_SURVEY_ANSWER'
export const SET_SURVEY_ANSWER_MULTI = 'SET_SURVEY_ANSWER_MULTI'
export const DELETE_SURVEY_ANSWER = 'DELETE_SURVEY_ANSWER'
export const RESET_SURVEY_ANSWERS = 'RESET_SURVEY_ANSWERS'

export const SET_SURVEY_FILES = 'SET_SURVEY_FILES'
export const RESET_SURVEY_FILES = 'RESET_SURVEY_FILES'

export const SET_SURVEY_TRANS = 'SET_SURVEY_TRANS'

export const SET_SURVEY_IS_VALID = 'SET_SURVEY_IS_VALID'

export const SET_SURVEY_DISPLAY_TYPE = 'SET_SURVEY_DISPLAY_TYPE'

export const SET_SURVEY_PAGE = 'SET_SURVEY_PAGE'
export const SET_SURVEY_LAST_PAGE = 'SET_SURVEY_LAST_PAGE'

export const SET_SURVEY_GROUP = 'SET_SURVEY_GROUP'
export const SET_SURVEY_LAST_GROUP = 'SET_SURVEY_LAST_GROUP'

export const SET_SURVEY_BGCOLOR = 'SET_SURVEY_BGCOLOR'

export const SET_SURVEY_THANKYOU_FILE = 'SET_SURVEY_THANKYOU_FILE'

export const SET_SURVEY_INFO = 'SET_SURVEY_INFO'