export const SURVEY_DISPLAY_TYPE_ONE_PAGE = 0
export const SURVEY_DISPLAY_TYPE_GROUP = 1
export const SURVEY_DISPLAY_TYPE_SUB_GROUP = 2
export const SURVEY_DISPLAY_TYPE_QUESTION = 9
export const SURVEY_DISPLAY_TYPE_QUESTION_IS_HORIZONTAL = 1