import {fieldTypes} from "../../../../constants/form-elements";

const primaryGuestMandatoryFields = [
    'firstname',
    'lastname',
    'email',
    'mobiletel'
]

const otherGuestMandatoryFields = [
    'firstname',
    'lastname'
]

const fieldGroupAccordionNames = {
    primary: 'primary',
    other: 'other'
}

const fieldGroupAccordions = [
    {
        label: '',
        key: fieldGroupAccordionNames.primary,
        defExpand: true
    },
    {
        label: 'str_moreDetails',
        key: fieldGroupAccordionNames.other,
        defExpand: false
    }
]

const fieldGroupNames = {
    personalInfo: 'personalInfo',
    identity: 'identity',
    invoice: 'invoice',
    others: 'others',
}

const fieldGroups = [
    {
        key: fieldGroupNames.personalInfo,
        label: 'str_personalInfo',
        labelShow: true,
        orderno: 0,
        accordionKey: fieldGroupAccordionNames.primary
    },
    {
        key: fieldGroupNames.identity,
        label: 'str_id',
        labelShow: true,
        orderno: 1,
        accordionKey: fieldGroupAccordionNames.primary
    },
    {
        key: fieldGroupNames.invoice,
        label: 'str_invoice',
        labelShow: true,
        orderno: 2,
        accordionKey: fieldGroupAccordionNames.other
    },
    {
        key: fieldGroupNames.others,
        label: 'str_others',
        labelShow: true,
        orderno: 3,
        accordionKey: fieldGroupAccordionNames.other
    },
]

const clientInitialState = {
    firstname: {
        label: 'str_firstName',
        key: 'firstname',
        groupKey: fieldGroupNames.personalInfo,
        value: '',
        isVisible: true,
        stateValue: false,
        type: fieldTypes.text,
        optionLabel: false,
        optionKey: false,
        defValKey: false,
        selectApi: false,
        isVerifyRequired: false,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: '',
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 3,
        },
    },
    lastname: {
        label: 'str_lastName',
        key: 'lastname',
        value: '',
        groupKey: fieldGroupNames.personalInfo,
        isVisible: true,
        stateValue: false,
        type: fieldTypes.text,
        optionLabel: false,
        optionKey: false,
        defValKey: false,
        selectApi: false,
        isVerifyRequired: false,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: false,
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 3,
        },
    },
    birthdate: {
        label: 'str_birthDate',
        key: 'birthdate',
        value: '',
        groupKey: fieldGroupNames.personalInfo,
        isVisible: true,
        stateValue: false,
        type: fieldTypes.date,
        optionLabel: false,
        optionKey: false,
        defValKey: false,
        selectApi: false,
        isVerifyRequired: false,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: '',
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 3,
        },
    },
    email: {
        label: 'str_email',
        key: 'email',
        value: '',
        groupKey: fieldGroupNames.personalInfo,
        isVisible: true,
        stateValue: false,
        type: fieldTypes.email,
        optionLabel: false,
        optionKey: false,
        defValKey: false,
        selectApi: false,
        isVerifyRequired: true,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: '',
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 3,
        },
    },
    mobiletel: {
        label: 'str_mobile',
        key: 'mobiletel',
        value: '',
        groupKey: fieldGroupNames.personalInfo,
        isVisible: true,
        stateValue: false,
        type: fieldTypes.tel,
        optionLabel: '',
        optionKey: false,
        defValKey: false,
        selectApi: false,
        isVerifyRequired: true,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: '',
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 3,
        },
    },
    gender: {
        label: 'str_gender',
        key: 'gender',
        value: '',
        groupKey: fieldGroupNames.personalInfo,
        isVisible: true,
        stateValue: false,
        type: fieldTypes.select,
        optionLabel: 'description',
        optionKey: 'code',
        defValKey: 'code',
        selectApi: 'transtype/view/gender',
        isVerifyRequired: false,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: '',
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 3,
        },
    },
    nationid: {
        label: 'str_nation',
        key: 'nationid',
        value: '',
        groupKey: fieldGroupNames.personalInfo,
        isVisible: true,
        stateValue: false,
        type: fieldTypes.select,
        optionLabel: 'description',
        optionKey: 'description',
        defValKey: 'id',
        selectApi: 'nation/view/list',
        isVerifyRequired: false,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: '',
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 3,
        },
    },
    langid: {
        label: 'str_language',
        key: 'langid',
        value: '',
        groupKey: fieldGroupNames.personalInfo,
        isVisible: true,
        stateValue: false,
        type: fieldTypes.select,
        optionLabel: 'description',
        optionKey: 'description',
        defValKey: 'id',
        selectApi: 'ralang/view/list',
        isVerifyRequired: false,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: '',
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 3,
        },
    },
    country: {
        label: 'str_country',
        key: 'country',
        value: '',
        groupKey: fieldGroupNames.personalInfo,
        isVisible: true,
        stateValue: false,
        type: fieldTypes.select,
        optionLabel: 'descineng',
        optionKey: 'descineng',
        defValKey: 'descineng',
        selectApi: 'country/view/list',
        trgValKey: false,
        trgQueryKey: false,
        trgValue: false,
        isVerifyRequired: false,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: '',
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 3,
        },
    },
    city: {
        label: 'str_city',
        key: 'city',
        value: '',
        groupKey: fieldGroupNames.personalInfo,
        isVisible: true,
        stateValue: false,
        type: fieldTypes.select,
        optionLabel: 'description',
        optionKey: 'description',
        defValKey: 'description',
        selectApi: 'city/view/list',
        trgValKey: 'descineng',
        trgQueryKey: 'country',
        trgValue: 'country',
        isVerifyRequired: false,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: '',
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 3,
        },
    },
    town: {
        label: 'str_town',
        key: 'town',
        value: '',
        groupKey: fieldGroupNames.personalInfo,
        isVisible: true,
        stateValue: false,
        type: fieldTypes.select,
        optionLabel: 'description',
        optionKey: 'description',
        defValKey: 'description',
        selectApi: 'town/view/list',
        trgValKey: 'description',
        trgQueryKey: 'citydesc',
        trgValue: 'city',
        isVerifyRequired: false,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: '',
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 3,
        },
    },
    district: {
        label: 'str_district',
        key: 'district',
        value: '',
        groupKey: fieldGroupNames.personalInfo,
        isVisible: true,
        stateValue: false,
        type: fieldTypes.select,
        optionLabel: 'description',
        optionKey: 'description',
        defValKey: 'description',
        selectApi: 'district/view/list',
        trgValKey: 'description',
        trgQueryKey: 'towndesc',
        trgValue: 'town',
        isVerifyRequired: false,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: '',
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 3,
        },
    },
    zip: {
        label: 'str_zip',
        key: 'zip',
        value: '',
        groupKey: fieldGroupNames.personalInfo,
        isVisible: true,
        stateValue: false,
        type: fieldTypes.text,
        optionLabel: false,
        optionKey: false,
        defValKey: false,
        selectApi: false,
        isVerifyRequired: false,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: '',
        gridBreakpoints: {
            xs: 12,
            sm: 3,
        },
    },
    address1: {
        label: 'str_address',
        key: 'address1',
        value: '',
        groupKey: fieldGroupNames.personalInfo,
        isVisible: true,
        stateValue: false,
        type: fieldTypes.text,
        optionLabel: false,
        optionKey: false,
        defValKey: false,
        selectApi: false,
        isVerifyRequired: false,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: '',
        gridBreakpoints: {
            xs: 12,
            sm: 9,
        },
    },
    tridno: {
        label: 'str_trIdNo',
        key: 'tridno',
        value: '',
        groupKey: fieldGroupNames.identity,
        isVisible: false,
        stateValue: false,
        type: fieldTypes.trid,
        optionLabel: false,
        optionKey: false,
        defValKey: false,
        selectApi: false,
        isVerifyRequired: true,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: '',
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 3,
        },
    },
    healthcode: {
        label: 'str_healthCode',
        key: 'healthcode',
        value: '',
        groupKey: fieldGroupNames.identity,
        isVisible: false,
        stateValue: false,
        type: fieldTypes.text,
        optionLabel: false,
        optionKey: false,
        defValKey: false,
        selectApi: false,
        isVerifyRequired: false,
        isShow: false,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: '',
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 3,
        },
    },
    idtypeid: {
        label: 'str_idType',
        key: 'idtypeid',
        value: '',
        groupKey: fieldGroupNames.identity,
        isVisible: true,
        stateValue: false,
        type: fieldTypes.select,
        optionLabel: 'description',
        optionKey: 'description',
        defValKey: 'id',
        selectApi: 'idtype/list',
        isVerifyRequired: false,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: '',
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 3,
        },
    },
    idno: {
        label: 'str_idNumber',
        key: 'idno',
        value: '',
        groupKey: fieldGroupNames.identity,
        isVisible: true,
        stateValue: false,
        type: fieldTypes.text,
        optionLabel: false,
        optionKey: false,
        defValKey: false,
        selectApi: false,
        isVerifyRequired: false,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: '',
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 3,
        },
    },
    birthplace: {
        label: 'str_birthPlace',
        key: 'birthplace',
        value: '',
        groupKey: fieldGroupNames.identity,
        isVisible: true,
        stateValue: false,
        type: fieldTypes.text,
        optionLabel: false,
        optionKey: false,
        defValKey: false,
        selectApi: false,
        isVerifyRequired: false,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: false,
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 3,
        },
    },
    idcard: {
        label: 'str_identification',
        key: 'idcard',
        value: '',
        groupKey: fieldGroupNames.identity,
        isVisible: true,
        stateValue: false,
        type: fieldTypes.upload,
        optionLabel: false,
        optionKey: 'IDENTIFICATION',
        trgQueryKey: 'hotelrefno',
        defValKey: 'mid',
        selectApi: false,
        isVerifyRequired: false,
        isResRequired: false,
        isBase: false,
        isError: false,
        errorText: '',
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 3,
        },
    },
    maritalstatus: {
        label: 'str_marriageStatus',
        key: 'maritalstatus',
        value: '',
        groupKey: fieldGroupNames.identity,
        isVisible: true,
        stateValue: false,
        type: fieldTypes.select,
        optionLabel: 'description',
        optionKey: 'code',
        defValKey: 'code',
        selectApi: 'transtype/view/maritalstatus',
        isVerifyRequired: false,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: '',
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 3,
        },
    },
    weddingdate: {
        label: 'str_marriageDate',
        key: 'weddingdate',
        value: '',
        groupKey: fieldGroupNames.identity,
        isVisible: false,
        stateValue: false,
        type: fieldTypes.date,
        optionLabel: false,
        optionKey: false,
        defValKey: false,
        selectApi: false,
        isVerifyRequired: false,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: '',
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 3,
        },
    },
    title: {
        label: 'str_invoiceTitle',
        key: 'title',
        value: '',
        groupKey: fieldGroupNames.invoice,
        isVisible: true,
        stateValue: false,
        type: fieldTypes.text,
        optionLabel: false,
        optionKey: false,
        defValKey: false,
        selectApi: false,
        isVerifyRequired: false,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: false,
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 3,
        },
    },
    taxoid: {
        label: 'str_taxOffice',
        key: 'taxoid',
        value: '',
        groupKey: fieldGroupNames.invoice,
        isVisible: true,
        stateValue: false,
        type: fieldTypes.select,
        optionLabel: 'description',
        optionKey: 'description',
        defValKey: 'id',
        selectApi: 'taxoffice/list',
        isVerifyRequired: false,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: '',
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 3,
        },
    },
    taxnumber: {
        label: 'str_taxNumber',
        key: 'taxnumber',
        value: '',
        groupKey: fieldGroupNames.invoice,
        isVisible: true,
        stateValue: false,
        type: fieldTypes.text,
        optionLabel: false,
        optionKey: false,
        defValKey: false,
        selectApi: false,
        isVerifyRequired: false,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: false,
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 3,
        },
    },
    occupationid: {
        label: 'str_profession',
        key: 'occupationid',
        value: '',
        groupKey: fieldGroupNames.others,
        isVisible: true,
        stateValue: false,
        type: fieldTypes.select,
        optionLabel: 'description',
        optionKey: 'description',
        defValKey: 'id',
        selectApi: 'clntjob/list',
        isVerifyRequired: false,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: '',
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 3,
        },
    },
    plateno: {
        label: 'str_plateNo',
        key: 'plateno',
        value: '',
        groupKey: fieldGroupNames.others,
        isVisible: true,
        stateValue: false,
        type: fieldTypes.text,
        optionLabel: false,
        optionKey: false,
        defValKey: false,
        selectApi: false,
        isVerifyRequired: false,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: false,
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 3,
        },
    },
    tel: {
        label: 'str_tel',
        key: 'tel',
        value: '',
        groupKey: fieldGroupNames.others,
        isVisible: true,
        stateValue: false,
        type: fieldTypes.tel,
        optionLabel: false,
        optionKey: false,
        defValKey: false,
        selectApi: false,
        isVerifyRequired: true,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: '',
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 3,
        },
    },
    signature: {
        label: 'str_signature',
        key: 'signature',
        value: '',
        groupKey: fieldGroupNames.others,
        isVisible: true,
        stateValue: false,
        type: fieldTypes.sign,
        optionLabel: 'signature',
        optionKey: 'SIGNATURE',
        trgQueryKey: 'hotelrefno',
        defValKey: 'mid',
        selectApi: false,
        isVerifyRequired: false,
        isResRequired: true,
        isBase: false,
        isError: false,
        errorText: '',
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 3,
        },
    },
    note: {
        label: 'str_note',
        key: 'note',
        value: '',
        groupKey: fieldGroupNames.others,
        isVisible: true,
        stateValue: false,
        type: fieldTypes.text,
        optionLabel: false,
        optionKey: false,
        defValKey: false,
        selectApi: false,
        isVerifyRequired: false,
        isResRequired: false,
        isBase: true,
        isError: false,
        errorText: false,
        gridBreakpoints: {
            xs: 12,
            sm: 6,
            md: 6,
        },
    }
}

export {
    primaryGuestMandatoryFields,
    otherGuestMandatoryFields,
    fieldGroupAccordions,
    fieldGroupNames,
    fieldGroups,
    clientInitialState,
}