let SERVER_CONST = {
    CLOUD_MASTER_NAME: 'hotech',
    CLOUD_PRODUCT_NAME: 'vimahotels',
    CLOUD_WEBKEY: 'cloud',
    PORTAL_WEBKEY: 'portal',
    CLOUD_PATH: '/cms/',
    INFO_DOMAIN: '/info/domain',
    REQ_TYPE: 'ReqType',
    REQ_TYPE_COMPANY: 'Company',
    WEBKEY_ERROR_MSG: 'There is no record for this web key -> ',
    WEBCMS_DATA: 'WEBCMS.DATA.',
    WEBCMS_COMPANY_INFO: 'WEBCMS.COMPANY_INFO',
    WEBCMS_TRANSTYPE: '9200135',
    DEFAULT_LANG: 'tr',
    PROTOCOL_SUFFIX: '://',
    HOST_CACHE_SUFFIX: '.CACHE',
    PROXY_CACHE_SUFFIX: '.PROXY',
    MS_CACHE_DATA_SUFFIX: 'MSCACHE.',
    CLOUD_URL: ['hotech', 'vimahotels'],
    CLOUD_OREST_URL: 'https://cloud.hotech.systems/orest',
    CLOUD_STATIC_URL: 'https://cloud.hotech.systems',
    DEV_OREST_URL: 'https://dev.hotech.dev/orest',
    DEV_STATIC_URL: 'https://dev.hotech.dev',
    DEV_WEBCMS: 'webcms',
    DEV_WEBCMS_WEBKEY: 'demo',
    CLOUD_HOTELMID: 99862,
    CLOUD_HOTELREFNO: 999999,
    CLOUD_HOTELGIDSTR: '7C3F5C18-1A47-4D4A-92E2-FE024ABED03E',
    BETA_OREST_URL: 'beta.hotech.systems',
    ONE_DAY_SECOND: 86400,
    CLOUD_PAYMENT_SERVICE_URL: 'https://cloud.hotech.systems/orest/ms/epay',
    DEV_PAYMENT_SERVICE_URL: 'http://192.168.0.223:8011/vpos/pay',
    TRIPADVISOR_FRAME_URL : 'https://www.tripadvisor.com/WidgetEmbed-collectreview',
    TRIPADVISOR_PARTNER_ID: '50DD3524204E43EF9B80C3E063B4CC99',
    TRIPADVISOR_SECURE_KEY : 'c2+5jMEqEY64*t6h2,b(lwktu?JlqQGb'
}

module.exports = SERVER_CONST
