export const UPDATESTATE = 'UPDATESTATE'
export const SET_TO_STATE = 'SET_TO_STATE'
export const PUSH_TO_STATE = 'PUSH_TO_STATE'
export const DELETE_FROM_STATE = 'DELETE_FROM_STATE'
export const ADD_TO_STATE = 'ADD_TO_STATE'
export const RESET_STATE = 'RESET_STATE'

export const initialState = {
    pageBuilder: {
        pageStep: 0,
        previousStep: 0,
        type: '',
        code: '',
        steps: [],
        hcmItemId: null,
        hcmCategory: {},
        hotelMid: 0,
        redisStdJson: {
            assets: '',
            header: {},
            footer: {},
            pages: [],
        },
        langCode: '',
        defaultLang: '',
        defaultLangId: 0,
        langId: 0,
        langDesc: '',
        assets: {
            images: {
                logo: '',
                altLogo: '',
                logoBanner: '',
                favIcon: '',
                background: '',
                poweredBy: '',
                thumbnail: ''
            },
            meta: {
                title: '',
                lang: 'en',
                dir: 'ltr',
                ibeurl: '',
                googleTag: '',
                googleAnalyticsTag: '',
                chatBox: '',
                fbVerificationCode: '',
                imageQuality: 0.5
            },
            font: {
                name: 'Arial',
                size: 10,
                bold: false,
                italic: false,
            },
            colors: {
                primary: {
                    main: '',
                    light: '',
                    dark: '',
                    contrastText: '',
                },
                secondary: {
                    main: '',
                    light: '',
                    dark: '',
                    contrastText: '',
                },
                message: {
                    main: '',
                    light: '',
                    dark: '',
                    contrastText: '',
                },
                button: {
                    main: '',
                    light: '',
                    dark: '',
                    contrastText: '',
                },
                slider: {
                    main: '',
                    light: '',
                    dark: '',
                    contrastText: '',
                },
            },
            icons: {
                phone: '',
                email: '',
                facebook: '',
                twitter: '',
                instagram: '',
                linkedin: ''
            }
        },
        logoUrl: '',
        altLogoUrl: '',
        logoBanner: '',
        faviconUrl: '',
        backgroundUrl: '',
        poweredByUrl: '',
        thumbnailUrl: '',
        phoneIconUrl: '',
        emailIconUrl: '',
        facebookIconUrl: '',
        twitterIconUrl: '',
        instagramIconUrl: '',
        linkedinIconUrl: '',
        footerOnly: false,
        page: {
            id: '',
            sections: [],
        },
        langsFile: {},
        email: {
            header: {},
            footer: {},
            body: [],
        },
        website: {
            header: {},
            footer: {},
            pages: [],
        },
        slider: {
            title: '',
            description: '',
            cta: '',
            gid: ''
        },
        faq: [],
        faqActiveTab: 'add',
        languages: [],
        translatedLanguages: [],
        isTemplate: false,
        emailWidth: 600,
        isSuperHotel: false,
        isSuperUser: false
    },
    registerStepper: {
        agencyListSearch: {
            isInitialized: false,
            isContinue: false,
            selectedAgency: null,
            inputAgencyValue: '',
        },
        isAdvanced: false,
        isCheckCompany: false,
        isPrivacyPolicy: false,
        moduleUseType: '',
        pageStep: 0,
        cacheToken: '',
        cacheHotelID: 0,
        backDropStatus: false,
        descriptionList: [],
        basics: {},
        agencyTypeList: [],
        agencyList: [],
        agencyChainList: [],
        moduleGroupList: [],
        reCaptcha: '',
        mapAddress: null,
        address: {},
        countryList: [],
        cityList: [],
        townList: [],
        countryID: 0,
        roomTypes: [],
        roomBedTypes: [],
        hcmItemID: 0,
        hcmRoomCatID: 0,
        hcmCategory: [],
        hcmFacilities: [],
        hcmItemTxt: [],
        hcmTxtSec: [],
        hcmFactSec: [],
        hcmItemImgCategory: [],
        hcmItemImgCategoryItems: [],
        hcmItemSlider: [],
        hcmItemSliderItems: [],
        hcmItemVidCategory: [],
        hcmItemVidCategoryItems: [],
        files: [],
        languages: [],
        cmsSlider: [],
        remarkGr: [],
        remarkList: [],
        hcmFact: [],
        hcmFactCategory: [],
        hcmFactItem: [],
        agencyInfo: [],
        layoutTabIndex: 0,
        remarkTabIndex: 0,
        facilitiesTabIndex: 0,
        descriptionTabIndex: 0,
        photosTabIndex: 0,
        roomSliderTabIndex: 0,
        videosTabIndex: 0,
        cmsSliderTabIndex: 0,
        photosNewOrderList: [],
        videosNewOrderList: [],
        photosGridDragAndDrop: false,
        videosGridDragAndDrop: false,
        orderSummary: {
            subtotal: 0,
            totalvat: 0,
            discountrate: 0,
            discount: 0,
            nettotal: 0,
            ordertotal: 0,
        },
        salesDiscounts: [],
    },
    website: {
        defaultLangCode: '',
        selectedLangCode: '',
        ccTel: '',
        defaultHeader: {},
        defaultFooter: {},
        defaultPages: [],
        languages: [],
        otherLangHeader: {},
        otherLangPages: [],
        otherLangFooter: {},
        assets: {},
        pageNotFound: false,
        selectedHeaderLink: ''
    },
    ibe: {
        hotelUiToken: false,
        hotelBookingInfo: false,
        hotelPaymentType: false,
        hotelBankIbanWarnMsg: false,
        hotelPaymentTypeAlert: false,
        bookingIsLoading: false,
        bookingIsDisable: false,
        bookingIsChange: false,
        bookingConfirmIsGroup: false,
        bookingConfirmReservno: false,
        bookingConfirmTransId: false,
        hotelBookingBackdrop: true,
        isMaxRoomError: false,
        bookingState: {
          adult: 1,
          child: 0,
          night: 1,
          stayDates: [null, null],
          refcode: false
        },
        bookingActiveStep: 0,
        roomSortVal: false,
        isHandleContinue: false,
        continueWithoutClientRecord: false,
        contactInfo: {
            firstName: {
                key: 'firstname',
                value: '',
                isrequired: true,
                iserror: false,
            },
            lastName: {
                key: 'lastname',
                value: '',
                isrequired: true,
                iserror: false,
            },
            mail: {
                key: 'email',
                value: '',
                isrequired: true,
                iserror: false,
            },
            phone: {
                key: 'mobiletel',
                value: '',
                isrequired: false,
                iserror: false,
            },
            birthDate: {
                key: 'birthdate',
                value: '',
                isrequired: false,
                iserror: false,
            },
            healthcode: {
                key: 'healthcode',
                value: '',
                isrequired: false,
                iserror: false,
            },
            note: {
                key: 'note',
                value: '',
                isrequired: false,
                iserror: false,
            }
        },
        flyTransfer: false,
        flyTransferInfo: false,
        flyTransferReturn: false,
        flyTransferReturnInfo: false,
        menuGroupAndProductList: false,
        acceptReservation: false,
        ibeWidgetListInitialized: false,
        guestInfoForm: true,
        guestInfoFormStatus: false,
        minStay: 1,
        maxAdult: 1,
        maxChild: 0,
        maxChildAge: 0,
        agencyid: 0,
        currencyid: 0,
        langid: 0,
        marketid: 0,
        paymentMethods: [],
        paytypeid: null,
        selectedPaymentType: null,
        selectedPaymentTypeId: null,
        selectedPaymentTypeMid: null,
        selectedPaymentIbanId: null,
        mailOrderInfo: false,
        creditCardInfo: false,
        bankTransfer: [],
        hotelinfo: [],
        roomTypeAttrList: [],
        selectedProducts: [],
        ibeTabPanel: 0,
        selectedDate: [null, null],
        night: null,
        selecttotalroom: 1,
        adult: 1,
        child: 0,
        childAges: [],
        diffCurrency: {
            use: false,
            value: false,
            isAlert: false
        },
        reservationConfirmDialog: false,
        isRoomCheck: false,
        clientPassword: false,
        clientsInfo: {
            clientid: false,
            firstName: '',
            firstNameError: false,
            lastName: '',
            lastNameError: false,
            mail: '',
            mailError: false,
            phone: '',
            birthDate: '',
            birthDateError: false,
            note: '',
            healthcode: ''
        },
        roomAvailabilityList: [],
        listOfSelectedRoomsQty: [],
        listOfSelectedRooms: {
            resmasterno: 0,
            roomList: [],
        },
        selectedRooms: [],
        searchid: '',
        listOfSelectedLogs: [],
    },
    ePayment: {},
    eConcierge: {},
    hgr: {},
    survey: {},
    hr: {},
    userPortal: {
        currentTask: null,
        isAllRequest: false,
        finishStatusID: 0,
        panelStatus: 0,
        myLevel: 5010621,
        userTaskRights: null,
        panels: {
            requestList: 0,
            requestDetail: 1,
            addNewRequest: 2,
        },
        currentTaskNotesLoading: false,
        request: [],
        defMyRequest: {},
        defMyRequestBase: {},
        defMyRequestNote: {},
        defMyRequestNoteBase: {},
        noteImages: false,
        defMyRequestNoteReply: {},
        defMyRequestNoteReplyBase: {},
        openNoteDialog: false,
        isEditNote: false,
        requestModuleList: [],
        requestIncidentList: [],
        currentTaskNotes: [],
        requestTransTypes: {
            devproject: [],
            raver: [],
            browser: [],
            ostype: [],
        },
        newRequestStepper: {
            reqSteps: {
                about: 0,
                details: 1,
                participants: 2
            },
            defaultDepartId: null,
            isSaveRequest: false,
            activeStep: 0,
            isRequestActive: false,
            useModuleActive: false,
            useRequestIncidentList: null,
            module: null,
            inputModuleValue: '',
            incident: null,
            inputIncidentValue: '',
            tsolution: [],
            requestTypes: [],
            isTransTypeTask: false,
            isTransTypeBug: false,
            isTransTypeTsForm: false,
            taskTypeList: [],
            taskType: '',
            tsType: '',
            fieldError: {
                modules: false,
                description: false,
                platform: false,
                version: false,
                ostype: false,
                browser: false,
                repsteps: false,
                result: false,
                expected: false,
            },
            participantList: [{
                empId: "",
                firstName: "",
                lastName: "",
                department: "",
                positionId: "",
                position: "",
                email: "",
                telephone: "",
                isDatabaseInfo: false,
            }],
            employeeList: [],
            selectedHotelRefNo: "",
            selectedHotelName: "",
            trainingModules: [],
            selectedModules: [],
            loadedModuleList: false,
            taskBugData: false,
            trainingType: "",
            trainingDepartId: "",
            isTrainingModulesSelected: false,
            isTrainingRequest: false,
            confirmTermsAndCondition: false,
            empHotelList: [],
            selectedHotelInfo: null
        },
        dashBoardOverview: {
            queryCounter: 0,
            requestTaskTotalCount: 0,
            requestTaskOpenCount: 0,
            requestTaskCloseCount: 0,
            bugTaskTotalCount: 0,
            bugTaskOpenCount: 0,
            bugTaskCloseCount: 0,
            techServiceTaskTotalCount: 0,
            techServiceTaskOpenCount: 0,
            techServiceTaskCloseCount: 0,
            otherTaskTotalCount: 0,
            otherTaskOpenCount: 0,
            otherTaskCloseCount: 0
        },
        loggedStatus: true,
        account: {
            paymentList: []
        }
    },
    supplierPortal: {

    },
    employeePortal: {
        openCvDialog: false,
        activeStep: 0,
        personalDataBase: false,
        educationList: [],
        workExpList: [],
        empRefList: [],
        empAbilityList: [],
        empLangList: [],
        empCv: false,
        empCvData: {},
        personalData: {
            firstname: {value: '', isError: false, required: true, helperText: ''},
            lastname: {value: '', isError: false, required: true, helperText: ''},
            tridno: {value: '', isError: false, required: false, helperText: ''},
            gender: {value: false, isError: false, required: true, helperText: ''},
            email: {value: '', isError: false, required: true, helperText: ''},
            mobiletel: {value: '', isError: false, required: true, helperText: ''},
            birthdate: {value: '', isError: false, required: false, helperText: ''},
            birthplace: {value: '', isError: false, required: false, helperText: ''},
            tel: {value: '', isError: false, required: false, helperText: ''},
            nationid: {value: false, isError: false, required: true, helperText: ''},
            address1: {value: '', isError: false, required: false, helperText: ''},
            address2: {value: '', isError: false, required: false, helperText: ''},
            city: {value: false, isError: false, required: false, helperText: ''},
            town: {value: false, isError: false, required: false, helperText: ''},
            gid: {value: false}
        },
        empEduData: false,
        empWorkData: false,
        empRefData: false,
        empAbilityData: false,
        empLangData: false,
    },
    guest: {
        //home screen
        homeList: {
            isLoading: false,
            langcode: false
        },
        hotelType: {
            data: false,
            chosenId: false,
            chosenCode: false,
            chosenTitle: false
        },
        homeSlider: {
            data: false,
        },
        offers: {
            data: false,
            deflimit: 4,
            limit: 4
        },
        activityRes: {        
            openDialog: false,
            selectedActivity: false,
            activeStep: 0,
            selectedDate: null,
            selectedTime: null
        },
        weeklyList: {
            data: false,
            langcode: false,
            chainid: false
        },
        nearbyList: {
            data: false,
            langcode: false,
            chainid: false
        },
        hotelList: {
            data: false,
            langcode: false,
            chainid: false
        },
        infoList: {
            data: false,
            langcode: false,
            chainid: false
        },
        infoListOneGroup: {
            groupName: false,
            id: false,
            data: false,
            langcode: false,
            chainid: false
        },
        otherInfoList: false,
        hotelFaq: {
            data: false,
            langcode: false,
            chainid: false
        },
        loyaltyAdvantages: {
            data: false,
            langcode: false
        },
        mapInfoList: {
            data: false,
            langcode: false,
            chainid: false
        },
        tabPanelHashCode: '',
        profile: {
            loadGuest: true,
            checkboxGroupAll: {},
            checkboxGroupAllBase: {},
            radioGroupAllGid: {},
            radioGroupAllGidBase: {}
        },
        myRequest: {
            openDialog: false,
            currentStep: 0,
            isSaving: false,
            requestTypeList: [],
            requestData: {
                accid: {value: null, isRequired: true, isError: false, helperText: false},
                transtype: {value: null, isRequired: true, isError: false, helperText: false},
                tsdescid: {value: null, isRequired: true, isError: false, helperText: false},
                note: {value: '', isRequired: true, isError: false, helperText: false},
                tscatid: {value: null, isRequired: false, isError: false, helperText: false},
                tstypeid: {value: null, isRequired: false, isError: false, helperText: false}
            },
            requestDataBase: {
                accid: {value: null, isRequired: true, isError: false, helperText: false},
                transtype: {value: null, isRequired: true, isError: false, helperText: false},
                tsdescid: {value: null, isRequired: true, isError: false, helperText: false},
                note: {value: '', isRequired: true, isError: false, helperText: false},
                tscatid: {value: null, isRequired: false, isError: false, helperText: false},
                tstypeid: {value: null, isRequired: false, isError: false, helperText: false}
            },
            fileList: [],
            tsDescFromDialog: null,
            requestNumber: '',
            steps: {
                requestType: 0,
                requestDescription: 1,
                confirm: 2
            },

        },
        allOtherGuestsComplete: false,
        otherGuestIsValidLoading: false,
        otherGuestIsValid: false,
        useKioskLanguage: false,
        loginTo: 45,
        isHotelListOpen: false,
        bonusTransPoints: 0,
        isSelectGift: false,
        memCardNext: null,
        //restaurant reservation
        totalPax: 1,
        totalChd: 0,
        strEventRules: false,
        eventResTotals: {},
        eventLocTransDateList: [],
        eventLocTransDate: 0,
        eventLocTransTime: 0,
        eventLocTransDateSlotList: false,
        menuGroupAndProductList: false,
        selectGuestProductList: [],
        selectGuestProductPropList: false,
        isRestaurantResTermsConfirm: false,
        clientReservation: false,
        reservBase: false,
        agencyProfilePhoto: false,
        clientProfilePhoto: false,
        clientLoyaltyCard: false,
        clientMid: 0,
        changeHotelName: '',
        changeHotelRefno: false,
        clientReservIsLoading: false,
        openLoginDialog: false,
        routerQueryState: false
    },
    destinationPortal: {
        portalList: [],
        notGroupedPortalList: [],
        selectedCategoryList: [],
        homeSlider: [],
        selectedHotel: null,
        selectedCategory: null,
        catId: "",
        dialogOpen: false,
        webKey: "",
        loginDialog: false,
        hotelCommentList: [],
        facilityList: [],
        reviewList: [],
        hotelStats: null,
        scrollIndex: 0,
        lastScrollIndex: 0
    },
    oLiveChat: {
        widgetVisibility: false,
        initialChatRenderState: true,
        renderChatEmoji: false,
        renderChatAttachment: false,
        rating: {
            figure: null,
            color: null
        },
        initialScreen: 0,
        previousChatMessages: [],
        userAuthData: {
            email: "",
            name: ""
        },
        userAuthDialogueVisbility: false
    },
    cloudWiki: {
        googleDocId: "home",
        navMenu: [],
        langCode: false
    },
    langEditor: {
        moduleList: false,
        selectModule: false,
        languageList: false,
        selectLanguageList: false,
        isLoadingLanguageSync: false,
        hcmLangTargetFileList: [],
        hcmLangTargetFileData: [],
        srcHmcLangData: [],
        srcHmcLangGid: false,
        targetLanguage: {},
        targetAvailableLanguage: {}
    },
    dynamicList: {}
}
